### PR TITLE
Migrate to eslint

### LINKED ISSUE #139: Migrate to ESLint from JSCS
http://eslint.org/blog/2016/07/jscs-end-of-life

Perhaps start of by using the `recommended` preset...

I am willing to do a PR in case this seems like a reasonable issue.

### PR DESCRIPTION
**Pull request by paazmaya**
Shall fix #139 
There are still 128 warnings left...

### CODE REVIEW

**Comment by paazmaya** [comment]
ESLint not supporting Node.js versions `0.10` nor `0.12`, hence failing on those at Travis

**Comment by hzoo** [comment]
Would be more work but we can do the same as what we did in babel https://github.com/babel/babel/pull/4680 (run lint as a separate build and only on latest node)

**Comment by markelog** [comment]
@paazmaya Nice. Looking forward to what comes next

@hzoo heh, didn't know if you still watching this repo

**Comment by hzoo** [comment]
@markelog Of course 😄  - sad I'm not really on the jscs gitter or anything but you should join the babel slack if you want!

**Comment by paazmaya** [comment]
How about checking that `node --version` does not begin with a zero and only then execute linting?

**Comment by hzoo** [comment]
It's actually really simple - just need to do something like https://github.com/babel/babili/pull/229/commits/cdc5deb8fd696f470e55172b54edf923889824c0

**Comment by paazmaya** [comment]
Looks like it was, really simple.
Thank you very much @hzoo!

**Comment by paazmaya** [comment]
It seems that is ESLint is only executed in one test job and that job has Node.js `7`

**Comment by graingert** [comment]
> ESLint not supporting Node.js versions 0.10 nor 0.12, hence failing on those at Travis

Support has ended for Node.js 0.10 and support ends for 0.12 next month

**Comment by paazmaya** [comment]
@graingert sure, but it might that some tools such as `cst` might decide to support them, but I certainly hope not, just in order to reduce the amount of supported versions...

Anyone from @cst would like to merge or comment if further changes needed?

**Comment by markelog** [comment]
> Anyone from @cst would like to merge or comment if further changes needed?

Did you saw my comments?

**Comment by paazmaya** [comment]
@markelog https://github.com/cst/cst/issues/139#issuecomment-256207807 ?
Should the `google` preset be setup?

**Comment by markelog** [comment]
@paazmaya I figured we since we used `google` preset before – https://github.com/cst/cst/blob/07673646e80eaa25c9c0fc5d28aa94f33c7e6219/.jscsrc#L20 it seems it would be better to continue to do that

**Comment by paazmaya** [comment]
Perhaps this is somewhat equal... https://github.com/google/eslint-config-google

**Comment by markelog** [comment]
Yeah, that's what I meant for you to use :)

**Comment by paazmaya** [comment]
Ok, well now that it is in place there are plenty of errors due to the use of `var`.

`1111 problems (1025 errors, 86 warnings)`

I will use `--fix` to autofix those and then shall see what is left...

**Comment by paazmaya** [comment]
After autofixing, there are `﻿﻿556 problems (470 errors, 86 warnings)` left.
Most of those are `require-jsdoc` and 9 errors are from somewhere else.

May I assume that the jsdoc requirement will not be fixed within this PR?

**Comment by markelog** [comment]
> Anyone from @cst would like to merge or comment if further changes needed?

Sorry, it seems I was expected to click additional button from github for you to see my comments

> May I assume that the jsdoc requirement will not be fixed within this PR?

Yeah.

But wait, we still need to support old node envs, so we definitely need to use `var`s still :/.

**Comment by markelog** [comment]
> made require-jsdoc a warning

How about make it "off" for now?

**Comment by markelog** [comment]
> But wait, we still need to support old node envs, so we definitely need to use vars still :/.

Ignore that comment :)

**Comment by markelog** [comment]
It seems we left with only couple of issues?

**Comment by graingert** [comment]
ah sorry @paazmaya my changes conflict with yours. You should rebase

**Comment by markelog** [comment]
Please use a `rebase` next time, it was a small nightmare to merge these things in, also fixed up all those warnings and tuned things a bit.

Thank you!

**Pull request closed without merging**
