### PR TITLE
Allow non code in JSXEmptyExpression

### PR DESCRIPTION
**Pull request by yihongang**
Currently comment-only JSX expressions are not allowed. I think they should be, as they are kind of why `JSXEmptyExpression` exist.

Reference: https://github.com/facebook/jsx/blob/master/AST.md

### CODE REVIEW

**Comment by yihongang** [comment]
About the babylon test failures, master currently already fails 42 tests. This PR fixes the last test failure

```
  42) babylon fixture tests :: jsx :: basic :: 10:
     Error: Expected end of node list but "CommentBlock" found
      at ElementAssert.assertEnd (src/elements/ElementAssert.js:152:19)
      at JSXEmptyExpression._acceptChildren (src/elements/types/JSXEmptyExpression.js:9:18)
      at JSXEmptyExpression._setChildren (src/elements/Element.js:638:14)
      at JSXEmptyExpression.Element (src/elements/Element.js:50:18)
      at JSXEmptyExpression.Node (src/elements/Node.js:11:33)
      at JSXEmptyExpression.Expression (src/elements/Expression.js:13:33)
      at new JSXEmptyExpression (src/elements/types/JSXEmptyExpression.js:4:29)
      at buildElementTreeItem (src/elementTree.js:144:24)
      at buildElementTreeItem (src/elementTree.js:117:45)
      at buildElementTreeItem (src/elementTree.js:117:45)
      at buildElementTreeItem (src/elementTree.js:117:45)
      at buildElementTreeItem (src/elementTree.js:117:45)
      at buildElementTree (src/elementTree.js:32:14)
      at Parser.parse (src/Parser.js:140:23)
      at parseAndGetProgram (test/utils.js:10:19)
      at runTest (test/3rdParty/index.js:11:9)
      at Context.<anonymous> (test/3rdParty/index.js:41:9)
```

**Comment by yihongang** [comment]
@markelog how do I work towards getting this merged?

regarding the failures, is the suggestion in https://github.com/cst/cst/issues/156 allowed?

**Comment by markelog** [comment]
Sorry, missed this, could you rebase?

**Comment by yihongang** [comment]
rebased

**Comment by markelog** [comment]
Awesome, thanks!

**Pull request merged**
