### PR TITLE
fix hang in class body parser

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by markelog** [comment]
What kind of hang you mean?

**Comment by graingert** [comment]
@markelog https://travis-ci.org/cst/cst/jobs/238429859

**Comment by graingert** [comment]
@markelog are you in IRC somewhere?

**Comment by markelog** [comment]
It seems we death with this in https://github.com/cst/cst/commit/ee17b3d601d931d045017c16bf0bbf7185da7b79

**Comment by graingert** [comment]
@markelog yup a plain git merge would have closed both PRs ;)

**Pull request closed without merging**
