### PR TITLE
add tests for assignment defaults

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
There should still be a test for:

```js
let param = parseAndGetStatementInFunctionParams(' { x: { y } = {} } = {} ')[0];
```

**Comment by graingert** [comment]
but I'm not sure how to fix that one

**Comment by markelog** [comment]
> but I'm not sure how to fix that one

You mean it doesn't parse?

**Comment by graingert** [comment]
@markelog correct

**Comment by markelog** [comment]
It seems we don't have an issue for it? You can also add test-case for it and skip it if you want

**Comment by graingert** [comment]
Sure we do it's here: https://github.com/cst/cst/issues/141 would appreciate some hints on how to fix it

**Comment by markelog** [comment]
At the first look I don't see any clear solutions

**Pull request merged**
