### PR TITLE
Add support for `ClassProperty`

### LINKED ISSUE #112: Support ClassProperty node types
```js
class X {
    prop = 15;
}
```
http://astexplorer.net/#/0yMv5k6Dnr

Ref: https://github.com/jscs-dev/node-jscs/issues/2240

### PR DESCRIPTION
**Pull request by markelog**
Fixes #112

### CODE REVIEW

**Comment by mdevils** [comment]
LGTM 👍

**Comment by hzoo** [comment]
@markelog I would add a test case for class property without assignment

```js
class ClassWithoutInits {
  myProp;
}
```

Probably not accounted for in the code

**Comment by markelog** [comment]
Good idea would you want to do that?

Also, maybe you could shed the light on what is the computed property?

**Comment by zxqfox** [comment]
Computed? Like:
```js
var foo = 'bar';
class X {
  [foo]: 'bar'
};

X.prototype.bar // 'bar'
```

**Comment by markelog** [comment]
Yeah, babelon can't deal with that, seems this only one of the "potential" behaviours

**Comment by zxqfox** [comment]
@markelog I'm not sure it's a good idea at all. What's a purpose of computed properties in classes? ;-)

**Comment by markelog** [comment]
That's above my paygrade :)

**Pull request merged**
