### PR TITLE
upgrade mocha

### PR DESCRIPTION
**Pull request by graingert**
This is for '--inspect'

### CODE REVIEW

**Comment by markelog** [comment]
> This is for '--inspect'

What is that?

Maybe we could update other packages as well?

**Comment by graingert** [comment]
@markelog --inspect lets you use the Chromium inspector for debugging

**Comment by graingert** [comment]
> Maybe we could update other packages as well? While we at it?

Yeah but I only needed this one, didn't want to upgrade jscs etc

**Comment by markelog** [comment]
Yeah, jscs would be better to left alone, since we probably deal with that in https://github.com/cst/cst/pull/140

Might be tedious process to update all deps, but with https://github.com/th0r/npm-upgrade it should be fast and simple. Wanna do it?

**Comment by graingert** [comment]
@markelog that's the only other one that's outdated (using npm outdated)

**Comment by markelog** [comment]
O really? Cool then

**Comment by graingert** [comment]
@markelog because you're using "^6.x" version specs

**Pull request merged**
